runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "wmi-wli-sv-research.appspot.com"

handlers:
# Matches requests to /images/... to files in static/images/...

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
